name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      node-version: ${{ matrix.node-version }}
    strategy:
      matrix:
        node-version: [20]
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.node-version }}
          path: ./output

      - name: Verify artifact contents
        run: ls -l ./output

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_SECRET }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./output
          push: true
          tags: ghcr.io/alidirani/git-action-ci:latest

